name: Lint

'on': pull_request

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v1
        with:
          node-version: '13.x'
      - name: Install dependencies
        run: yarn install
      - name: Prettier lint
        run: yarn lint
