name: Publish

'on':
  push:
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v1
        with:
          node-version: '13.x'
      - name: Install dependencies
        run: yarn install
      - name: Babel transpile
        run: yarn build
      - name: Publish to NPM
        run: yarn publish --non-interactive
        env:
          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
